export const ADD_CHANNEL_SUCCESS = 'ADD_CHANNEL_SUCCESS';
export const REMOVE_CHANNEL = 'REMOVE_CHANNEL';

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const CHANGE_FILTER_STR = 'CHANGE_FILTER_STR';
export const CHANGE_ADD_STR = 'CHANGE_ADD_STR';
